k8s provision only in CSE (#2881)

diff --git a/parts/k8s/kubernetesmastercustomdata.yml b/parts/k8s/kubernetesmastercustomdata.yml
--- a/parts/k8s/kubernetesmastercustomdata.yml
+++ b/parts/k8s/kubernetesmastercustomdata.yml
@@ -348,11 +348,20 @@ MASTER_ARTIFACTS_CONFIG_PLACEHOLDER
     #!/bin/bash
     set -x
     source /opt/azure/containers/provision_source.sh
+    # TODO standardize/generalize CSE exit codes
+    ERR_ETCD_DOWNLOAD_TIMEOUT=12
+    ERR_SYSTEMCTL_ENABLE_FAIL=3
     ETCD_VER=v{{WrapAsVariable "etcdVersion"}}
     DOWNLOAD_URL={{WrapAsVariable "etcdDownloadURLBase"}}
     retrycmd_get_tarball 60 1 /tmp/etcd-${ETCD_VER}-linux-amd64.tar.gz ${DOWNLOAD_URL}/etcd-${ETCD_VER}-linux-amd64.tar.gz
+    if [ $? -ne 0 ]; then
+        exit $ERR_ETCD_DOWNLOAD_TIMEOUT
+    fi
     tar xzvf /tmp/etcd-${ETCD_VER}-linux-amd64.tar.gz -C /usr/bin/ --strip-components=1
     retrycmd_if_failure 10 1 3 systemctl enable etcd.service
+    if [ $? -ne 0 ]; then
+        exit $ERR_SYSTEMCTL_ENABLE_FAIL
+    fi
     sudo sed -i "1iETCDCTL_ENDPOINTS=https://127.0.0.1:2379" /etc/environment
     sudo sed -i "1iETCDCTL_CA_FILE={{WrapAsVariable "etcdCaFilepath"}}" /etc/environment
     sudo sed -i "1iETCDCTL_KEY_FILE={{WrapAsVariable "etcdClientKeyFilepath"}}" /etc/environment
@@ -397,33 +406,8 @@ coreos:
         ExecStart=/opt/azure/containers/provision-setup.sh
 {{else}}
 runcmd:
-# the first arg is the number of retries, the second arg is the wait duration between two retries and the rest of the args are the cmd to run
 - set -x
-- . /opt/azure/containers/provision_source.sh
-- wait_for_file 1800 1 /opt/azure/containers/certs.ready
-- /opt/azure/containers/setup-etcd.sh > /opt/azure/containers/setup-etcd.log 2>&1
-- retrycmd_if_failure 20 5 5 apt-mark hold walinuxagent {{GetKubernetesMasterPreprovisionYaml}}
-- /opt/azure/containers/mountetcd.sh
-- systemctl_restart 10 1 5 etcd
-- MEMBER="$(sudo etcdctl member list | grep -E {{WrapAsVerbatim "variables('masterVMNames')[copyIndex(variables('masterOffset'))]"}} | cut -d{{WrapAsVariable "singleQuote"}}:{{WrapAsVariable "singleQuote"}} -f 1)"
-- retrycmd_if_failure 10 1 5 sudo etcdctl member update ${MEMBER} {{WrapAsVerbatim "variables('masterEtcdPeerURLs')[copyIndex(variables('masterOffset'))]"}}
-- retrycmd_if_failure 5 1 10 curl --cacert /etc/kubernetes/certs/ca.crt --cert /etc/kubernetes/certs/etcdclient.crt --key /etc/kubernetes/certs/etcdclient.key --retry 5 --retry-delay 10 --retry-max-time 10 --max-time 60 "{{WrapAsVerbatim "variables('masterEtcdClientURLs')[copyIndex(variables('masterOffset'))]"}}"/v2/machines
-- apt_get_update
-- retrycmd_if_failure 5 1 120 apt-get install -y apt-transport-https ca-certificates iptables iproute2 socat util-linux mount ebtables ethtool init-system-helpers
-- retrycmd_if_failure_no_stats 180 1 5 curl -fsSL https://aptdocker.azureedge.net/gpg > /tmp/aptdocker.gpg
-- retrycmd_if_failure 10 1 5 apt-key add /tmp/aptdocker.gpg
-- echo "deb {{WrapAsVariable "dockerEngineDownloadRepo"}} ubuntu-xenial main" | sudo tee /etc/apt/sources.list.d/docker.list
-- "echo \"Package: docker-engine\nPin: version {{WrapAsVariable "dockerEngineVersion"}}\nPin-Priority: 550\n\" > /etc/apt/preferences.d/docker.pref"
-- apt_get_update
-- retrycmd_if_failure 20 1 120 apt-get install -y ebtables docker-engine
-- echo "ExecStartPost=/sbin/iptables -P FORWARD ACCEPT" >> /etc/systemd/system/docker.service.d/exec_start.conf
-- touch /opt/azure/containers/dockerinstall.complete
-- mkdir -p /etc/kubernetes/manifests
-- usermod -aG docker {{WrapAsVariable "username"}}
-- retrycmd_if_failure 20 1 10 /usr/lib/apt/apt.systemd.daily
-{{if EnableAggregatedAPIs}}
-- bash /etc/kubernetes/generate-proxy-certs.sh
-{{end}}
-- retrycmd_if_failure 20 1 5 apt-mark unhold walinuxagent
-- touch /opt/azure/containers/runcmd.complete
+- timeout 10 apt-mark hold walinuxagent{{GetKubernetesMasterPreprovisionYaml}}
+- timeout 10 apt-mark unhold walinuxagent
+- mkdir -p /var/log/azure && touch /var/log/azure/cloud-init.complete
 {{end}}
